version: '1'
services:
  local-mysql:
    image: arm64v8/mysql:8.0
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  local-mongo:
    image: arm64v8/mongo:latest
    platform: linux/arm64/v8
    ports:
      - 27017:27017
  local-rabbit:
    image: apple037037/rabbitmq-delayed-arm64:latest
    platform: linux/arm64/v8
    ports:
      - 5672:5672
      - 15672:15672
  local-redis:
    image: arm64v8/redis:latest
    platform: linux/arm64/v8
    ports:
      - 6379:6379
  local-phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    platform: linux/arm64/v8
    environment:
      PMA_HOST: local-mysql
      PMA_PORT: 3306
    ports:
      - 7777:80
  local-zipkin:
    image: openzipkin/zipkin:latest
    platform: linux/arm64/v8
    ports:
      - 9411:9411